from django.conf.urls.defaults import url, patterns

from zorna.notes import views


urlpatterns = patterns('',
                       url(r'^home/$',
                           views.notes_home_view,
                           name='notes_home_view'),
                       url(r'^browse/categories/(?P<category>\d+)/$',
                           views.dirlist_categories,
                           name='dirlist_categories'),
                       url(r'^browse/categories/$',
                           views.dirlist_categories,
                           name='dirlist_categories'),
                       url(r'^browse/shared/categories/$',
                           views.dirlist_shared,
                           name='dirlist_shared'),
                       url(r'^view/notes/$',
                           views.dirlist_category,
                           name='dirlist_category'),
                       url(r'^add/category/$',
                           views.notes_add_category,
                           name='notes_add_category'),
                       url(r'^rename/category/$',
                           views.notes_rename_category,
                           name='notes_rename_category'),
                       url(r'^add/note/$',
                           views.notes_add_note,
                           name='notes_add_note'),
                       url(r'^edit/note/$',
                           views.notes_edit_note,
                           name='notes_edit_note'),
                       url(r'^note/file/(?P<file_id>\d+)/$',
                           views.get_note_attachment,
                           name='get_note_attachment'),
                       url(r'^share/category/(?P<category>\d+)/$',
                           views.notes_share_category,
                           name='notes_share_category'),
                       )
