from django.conf.urls.defaults import url, patterns

from zorna.pages import views


urlpatterns = patterns('',
                       url(r'^fmbrowser/home/$',
                           views.fmbrowser_home,
                           name='fmbrowser_home'),
                       url(r'^fmbrowser/browse/files/$',
                           views.dirlist_files,
                           name='dirlist_files'),
                       url(r'^fmbrowser/browse/templates/$',
                           views.dirlist_templates,
                           name='dirlist_templates'),
                       url(r'^fmbrowser/edit/template/$',
                           views.edit_template,
                           name='edit_template'),
                       url(r'^fmbrowser/edit/file/$',
                           views.edit_source_file,
                           name='edit_source_file'),
                       url(r'^fmbrowser/edit/page/$',
                           views.edit_page,
                           name='edit_page'),
                       url(r'^fmbrowser/browse/folder/files/$',
                           views.dirlist_folder_files,
                           name='dirlist_folder_files'),
                       url(r'^fmbrowser/browse/folder/templates/$',
                           views.dirlist_folder_templates,
                           name='dirlist_folder_templates'),
                       url(r'^fmbrowser/clone/webpage/$',
                           views.clone_webpage,
                           name='clone_webpage'),
                       url(r'^fmbrowser/delete/webpage/$',
                           views.delete_webpage,
                           name='delete_webpage'),
                       url(r'^fmbrowser/rename/webpage/$',
                           views.rename_webpage,
                           name='rename_webpage'),
                       url(r'^fmbrowser/past/webpage/$',
                           views.past_webpage,
                           name='past_webpage'),
                       url(r'^fmbrowser/manage/folder/$',
                           views.manage_folder,
                           name='manage_folder'),
                       url(r'^preview/(?P<path>.*)$', 
                           views.preview_page,
                           name='preview_page'),
                       )
