
ZORNA_GROUP_PUBLIC = 1
ZORNA_GROUP_ANONYMOUS = 2
ZORNA_GROUP_REGISTERED = 3


ZORNA_PERMISSIONS_DENY = 0
ZORNA_PERMISSIONS_DENY_CHILDS = 1
ZORNA_PERMISSIONS_ALLOW = 2
ZORNA_PERMISSIONS_ALLOW_CHILDS = 3