from django.conf.urls.defaults import url, patterns

from zorna.faq import views


urlpatterns = patterns('',
                       url(r'^list/$',
                           views.list_faqs,
                           name='list_faqs'),                       
                       url(r'^add/$',
                           views.admin_add_faq,
                           name='admin_add_faq'),
                       url(r'^edit/(?P<faq>\d+)/$',
                           views.admin_edit_faq,
                           name='admin_edit_faq'),
                       url(r'^manager/list/$',
                           views.manager_list_faqs,
                           name='manager_list_faqs'),                       
                       url(r'^manager/edit/(?P<faq>\d+)/$',
                           views.manager_edit_faq,
                           name='manager_edit_faq'),
                       url(r'^manager/categories/list/(?P<faq>\d+)/$',
                           views.manager_faq_list_categories,
                           name='manager_faq_list_categories'),                       
                       url(r'^manager/category/add/(?P<faq>\d+)/$',
                           views.manager_faq_add_category,
                           name='manager_faq_add_category'),
                       url(r'^manager/category/edit/(?P<category>\d+)/$',
                           views.manager_faq_edit_category,
                           name='manager_faq_edit_category'),
                       url(r'^manager/questions/list/(?P<category>\d+)/$',
                           views.manager_faq_list_questions,
                           name='manager_faq_list_questions'),
                       url(r'^manager/question/add/(?P<faq>\d+)/$',
                           views.manager_faq_add_question,
                           name='manager_faq_add_question'),
                       url(r'^manager/question/add/(?P<faq>\d+)/(?P<category>\d+)/$',
                           views.manager_faq_add_question,
                           name='manager_faq_add_question'),
                       url(r'^manager/question/edit/(?P<question>\d+)/$',
                           views.manager_faq_edit_question,
                           name='manager_faq_edit_question'),
                       url(r'^sort_questions/(?P<category>\d+)/$',
                           views.sort_faq_questions,
                           name='sort_faq_questions'),  
                       url(r'^sort_categories/(?P<faq>\d+)/$',
                           views.sort_faq_categories,
                           name='sort_faq_categories'),                     
                       url(r'^(?P<faqslug>.*)/$',
                           views.browse_faq,
                           name='browse_faq'),                     
                       )
